title = "gitleaks config"

[allowlist]
description = "Allow listed matches"
paths = [
    ".*\\.test\\.ts$",
    ".*\\.test\\.tsx$",
    ".*/test/.*",
    "venv/.*",                # Allow top-level venv if present
    "api/python/venv/.*"       # Allow venv nested under api/python
]

[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(key|api|token|secret|client|passwd|password|auth|access)(.{0,20})([0-9a-zA-Z-_]{16,45})(['|"|\n])''' 